# Generated by Django 2.1.7 on 2019-03-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='WebsiteUser',
        ),
    ]
